// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannedCard } from "./ScannedCard";

export type AugmentScan = { cards: Array<ScannedCard>, championId: number, message: string | null, };
