// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Badge = "mvp" | "ace" | "penta" | "quadra" | "unkillable" | "firstBlood" | "topDamage" | "vision" | "farmer" | "tank" | "teamplayer";
