// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectSlot } from "./SelectSlot";

export type ChampSelect = { queueId: number, phase: string, timeLeftMs: number, myTeam: Array<SelectSlot>, theirTeam: Array<SelectSlot>, myBans: Array<number>, theirBans: Array<number>, bench: Array<number>, };
