// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AugmentStat } from "./AugmentStat";

export type ChampionAugments = { championId: number, games: number, wins: number, augments: Array<AugmentStat>, };
