// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Summoner } from "./Summoner";

export type ClientStatus = { "state": "disconnected", summoner: Summoner | null, } | { "state": "connected", summoner: Summoner, phase: string, };
