// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InGamePlayer = { riotId: string, champion: string, teamId: number, level: number, items: Array<number>, gold: number, kills: number, deaths: number, assists: number, cs: number, wardScore: number, dead: boolean, respawnIn: number, keystone: number, subStyle: number, spells: Array<string>, };
