// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InGamePlayer } from "./InGamePlayer";
import type { ObjectiveTimer } from "./ObjectiveTimer";

export type InGame = { gameTime: number, mode: string, map: number, me: string, myGold: number, players: Array<InGamePlayer>, timers: Array<ObjectiveTimer>, };
