// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChampionCount } from "./ChampionCount";
import type { PlayerBadge } from "./PlayerBadge";
import type { RecentGame } from "./RecentGame";
import type { RoleCount } from "./RoleCount";
import type { Standing } from "./Standing";

export type LivePlayer = { puuid: string, teamId: number, championId: number, gameName: string, tagLine: string, level: number, position: string, rank: Standing | null, peak: Standing | null, lastSeason: Standing | null, masteryLevel: number, masteryPoints: number, recentGames: number, recentWins: number, recentKda: Array<number>, championGames: number, championWins: number, championKda: Array<number>, recent: Array<RecentGame>, mainRole: string, roles: Array<RoleCount>, topChampions: Array<ChampionCount>, dayGames: number, dayWins: number, streak: number, badges: Array<PlayerBadge>, isMe: boolean, spells: Array<string>, spellIds: Array<number>, keystone: number, subStyle: number, };
