// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LivePlayer } from "./LivePlayer";

export type LiveGame = { gameId: number, queueId: number, players: Array<LivePlayer>, };
