// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LpKind } from "./LpKind";
import type { Queue } from "./Queue";
import type { Standing } from "./Standing";

export type LpEntry = { id: number, queue: Queue, kind: LpKind, gameId: number | null, championId: number | null, win: boolean | null, delta: number | null, after: Standing, kills: number | null, deaths: number | null, assists: number | null, recordedAt: number, };
