// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchEvent } from "./MatchEvent";
import type { PlayerDetail } from "./PlayerDetail";
import type { TeamDetail } from "./TeamDetail";

export type MatchDetail = { gameId: number, queueId: number, createdAt: number, durationSec: number, patch: string, teams: Array<TeamDetail>, players: Array<PlayerDetail>, goldDiff: Array<number>, events: Array<MatchEvent>, };
