// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Badge } from "./Badge";

export type MatchSummary = { gameId: number, queueId: number, championId: number, champLevel: number, position: string, win: boolean, remake: boolean, kills: number, deaths: number, assists: number, killParticipation: number, cs: number, items: Array<number>, spells: Array<number>, keystone: number, subStyle: number, durationSec: number, createdAt: number, lpDelta: number | null, badges: Array<Badge>, };
