// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";

export type MatchEvent = { atMs: number, kind: EventKind, teamId: number, killer: number, victim: number, assists: Array<number>, detail: string, };
