// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObjectiveTimer = { kind: string, label: string, teamId: number, respawnAt: number, };
