// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Badge } from "./Badge";

export type PlayerDetail = { participantId: number, teamId: number, puuid: string, gameName: string, tagLine: string, championId: number, champLevel: number, position: string, spells: Array<number>, items: Array<number>, primaryStyle: number, subStyle: number, perks: Array<number>, kills: number, deaths: number, assists: number, cs: number, gold: number, damageToChampions: number, damageTaken: number, visionScore: number, wardsPlaced: number, controlWards: number, win: boolean, largestMultiKill: number, firstBlood: boolean, badges: Array<Badge>, augments: Array<number>, };
