// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Queue } from "./Queue";
import type { Standing } from "./Standing";

export type RankEntry = { queue: Queue, standing: Standing, capturedAt: number, };
