// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentGame = { championId: number, win: boolean, kills: number, deaths: number, assists: number, queueId: number, createdAt: number, };
