// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScannedCard = { augmentId: number, x: number, y: number, size: number, confidence: number, };
