// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LivePlayer } from "./LivePlayer";

export type SelectSlot = { cellId: number, championId: number, locked: boolean, position: string, gameName: string, tagLine: string, hidden: boolean, isMe: boolean, spells: Array<number>, scout: LivePlayer | null, };
