// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Standing = { tier: string, division: string, lp: number, wins: number, losses: number, };
