// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Summoner = { puuid: string, gameName: string, tagLine: string, level: number, profileIconId: number, };
