// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamDetail = { teamId: number, win: boolean, bans: Array<number>, towers: number, dragons: number, barons: number, heralds: number, grubs: number, inhibitors: number, };
