// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetKind } from "./WidgetKind";

export type WidgetConfig = { kind: WidgetKind, visible: boolean, locked: boolean, opacity: number, x: number, y: number, };
