// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetConfig } from "./WidgetConfig";

export type WidgetSettings = { enabled: boolean, widgets: Array<WidgetConfig>, };
